// <auto-generated />
using System;
using APBD_Test.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APBD_Test.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250609110624_MatchMigration")]
    partial class MatchMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APBD_Test.Models.Map", b =>
                {
                    b.Property<int>("MapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MapId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MapId");

                    b.ToTable("Maps");

                    b.HasData(
                        new
                        {
                            MapId = 1,
                            Name = "Map 1",
                            Type = "Political"
                        },
                        new
                        {
                            MapId = 2,
                            Name = "Map 2",
                            Type = "Physical"
                        },
                        new
                        {
                            MapId = 3,
                            Name = "Map 3",
                            Type = "Topographic"
                        });
                });

            modelBuilder.Entity("APBD_Test.Models.Match", b =>
                {
                    b.Property<int>("MatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MatchId"));

                    b.Property<decimal?>("BestRating")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal");

                    b.Property<int>("MapId")
                        .HasColumnType("int");

                    b.Property<DateTime>("MatchDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Team1Score")
                        .HasColumnType("int");

                    b.Property<int>("Team2Score")
                        .HasColumnType("int");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.HasKey("MatchId");

                    b.HasIndex("MapId");

                    b.HasIndex("TournamentId");

                    b.ToTable("Matches");

                    b.HasData(
                        new
                        {
                            MatchId = 1,
                            BestRating = 3.22m,
                            MapId = 1,
                            MatchDate = new DateTime(2020, 1, 1, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Team1Score = 20,
                            Team2Score = 30,
                            TournamentId = 1
                        },
                        new
                        {
                            MatchId = 2,
                            BestRating = 2.12m,
                            MapId = 3,
                            MatchDate = new DateTime(2022, 5, 2, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Team1Score = 10,
                            Team2Score = 16,
                            TournamentId = 2
                        },
                        new
                        {
                            MatchId = 3,
                            BestRating = 1.15m,
                            MapId = 2,
                            MatchDate = new DateTime(2022, 5, 3, 9, 45, 0, 0, DateTimeKind.Unspecified),
                            Team1Score = 15,
                            Team2Score = 19,
                            TournamentId = 2
                        },
                        new
                        {
                            MatchId = 4,
                            MapId = 2,
                            MatchDate = new DateTime(2025, 3, 5, 10, 5, 0, 0, DateTimeKind.Unspecified),
                            Team1Score = 24,
                            Team2Score = 12,
                            TournamentId = 3
                        });
                });

            modelBuilder.Entity("APBD_Test.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerId"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PlayerId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("APBD_Test.Models.PlayerMatch", b =>
                {
                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("MVPs")
                        .HasColumnType("int");

                    b.Property<decimal>("Rating")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal");

                    b.HasKey("MatchId", "PlayerId");

                    b.HasIndex("PlayerId");

                    b.ToTable("Player_Match");
                });

            modelBuilder.Entity("APBD_Test.Models.Tournament", b =>
                {
                    b.Property<int>("TournamentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TournamentId"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("TournamentId");

                    b.ToTable("Tournaments");

                    b.HasData(
                        new
                        {
                            TournamentId = 1,
                            EndDate = new DateTime(2020, 1, 1, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Tournament 1",
                            StartDate = new DateTime(2020, 1, 1, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TournamentId = 2,
                            EndDate = new DateTime(2022, 5, 4, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Tournament 2",
                            StartDate = new DateTime(2022, 5, 1, 8, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TournamentId = 3,
                            EndDate = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Tournament 3",
                            StartDate = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("APBD_Test.Models.Match", b =>
                {
                    b.HasOne("APBD_Test.Models.Map", "Map")
                        .WithMany("Matches")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APBD_Test.Models.Tournament", "Tournament")
                        .WithMany("Matches")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Map");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("APBD_Test.Models.PlayerMatch", b =>
                {
                    b.HasOne("APBD_Test.Models.Match", "Match")
                        .WithMany("PlayerMatches")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APBD_Test.Models.Player", "Player")
                        .WithMany("PlayerMatches")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("APBD_Test.Models.Map", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("APBD_Test.Models.Match", b =>
                {
                    b.Navigation("PlayerMatches");
                });

            modelBuilder.Entity("APBD_Test.Models.Player", b =>
                {
                    b.Navigation("PlayerMatches");
                });

            modelBuilder.Entity("APBD_Test.Models.Tournament", b =>
                {
                    b.Navigation("Matches");
                });
#pragma warning restore 612, 618
        }
    }
}
